-- Create the tasks table
create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  course_id bigint references public.courses(id),
  title text not null,
  description text,
  due_date timestamp with time zone,
  type text check (type in ('Assignment', 'Quiz', 'Chapter Test', 'Exam')) not null,
  status text check (status in ('To Do', 'In Progress', 'Done')) default 'To Do' not null
);

-- Enable Row Level Security (RLS)
alter table public.tasks enable row level security;

-- Policy for users to view their own tasks
create policy "Users can view their own tasks"
on public.tasks for select
using (auth.uid() = user_id);

-- Policy for users to create their own tasks
create policy "Users can insert their own tasks"
on public.tasks for insert
with check (auth.uid() = user_id);

-- Policy for users to update their own tasks
create policy "Users can update their own tasks"
on public.tasks for update
using (auth.uid() = user_id);

-- Policy for users to delete their own tasks
create policy "Users can delete their own tasks"
on public.tasks for delete
using (auth.uid() = user_id);
