-- Create the tasks table
create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  course_id bigint references public.courses(id),
  title text not null,
  description text,
  due_date timestamp with time zone,
  type text check (type in ('Assignment', 'Quiz', 'Chapter Test', 'Exam')) not null,
  status text check (status in ('To Do', 'In Progress', 'Done')) default 'To Do' not null
);

-- Enable Row Level Security (RLS)
alter table public.tasks enable row level security;

-- Policy for users to view their own tasks
create policy "Users can view their own tasks"
on public.tasks for select
using (auth.uid() = user_id);

-- Policy for users to create their own tasks
create policy "Users can insert their own tasks"
on public.tasks for insert
with check (auth.uid() = user_id);

-- Policy for users to update their own tasks
create policy "Users can update their own tasks"
on public.tasks for update
using (auth.uid() = user_id);

-- Policy for users to delete their own tasks
create policy "Users can delete their own tasks"
on public.tasks for delete
using (auth.uid() = user_id);

-- UPDATES FOR ADMIN AND GLOBAL TASKS

-- Add role to profiles
alter table public.profiles add column if not exists role text default 'student' check (role in ('student', 'admin'));

-- Add is_global to tasks
alter table public.tasks add column if not exists is_global boolean default false;

-- Drop old select policy to replace it
drop policy if exists "Users can view their own tasks" on public.tasks;

-- Allow users to view their own tasks AND global tasks
create policy "Users can view their own or global tasks"
on public.tasks for select
using (auth.uid() = user_id or is_global = true);

-- Allow admins to insert global tasks
create policy "Admins can insert global tasks"
on public.tasks for insert
with check (
  (select role from public.profiles where id = auth.uid()) = 'admin'
  and is_global = true
);

-- Allow admins to update global tasks
create policy "Admins can update global tasks"
on public.tasks for update
using (
  (select role from public.profiles where id = auth.uid()) = 'admin'
  and is_global = true
);

-- Allow admins to delete global tasks
create policy "Admins can delete global tasks"
on public.tasks for delete
using (
  (select role from public.profiles where id = auth.uid()) = 'admin'
  and is_global = true
);
